/**
 * Copyright (c) OneKey, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  ExtensionSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Extension', // generate sidebar slice from the docs folder (or versioned_docs/<version>)
    },
  ],
  ConnectSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Connect', // generate sidebar slice from the docs folder (or versioned_docs/<version>)
    },
  ]
};
